export const REST_MENU = "/admin/menu"
export const REST_CATEGORY = "/admin/item-category"
export const REST_RESERVATION = "/reservation"
export const REST_NOTIFICATION = "/admin/notification"
export const ASSET = "/admin/asset"
